name            : cupertino_stackview
description     : A very easy-to-use navigation tool/widget for having iOS 13 style stacks.
version         : 1.0.1
author          : Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository      : https://github.com/aliyigitbireroglu/flutter-cupertino-stackview
homepage        : https://www.cosmossoftware.coffee

environment     :
  sdk: ">=2.2.2 <3.0.0"

dependencies    :
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter         :
